### ISSUE TITLE
Probably misplace of watcher folder and some suggestions

### ISSUE THREAD

**Issue by okan-instrumentl** [flexagoon/aw-watcher-gnome#1]
I followed up the instructions but they are not really clear:

- In step three it says:
	>Copy the dist/aw-watcher-gnome directory to your ActivityWatch directory.

	But the actual file name is `aw_watcher_gnome`. It was really hard to find.  
	- Where should I put this exactly? I tried to put in `config` folder  and `opt/activity-watch` but no luck.

- I came across your gnome shell extension, is that meant to be installed with that watcher or  something different?

- In step 5, you mentioned the edits in the `toml` file. But should I uncomment these lines? Maybe this is a common knowledge of `toml` files but I guess there will be a plenty of people that don't know that. I did learn that answer with a couple of trial and errors.

And last of all, I'm stuck with error now: 
```
2022-12-19 15:20:45 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2022-12-19 15:20:45 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-qt.desktop  (aw_qt.manager:64)
2022-12-19 15:20:45 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:64)
2022-12-19 15:20:45 [INFO ]: Found 4 bundled modules  (aw_qt.manager:85)
2022-12-19 15:20:45 [INFO ]: Found 4 system modules  (aw_qt.manager:119)
2022-12-19 15:20:45 [ERROR]: Module aw-watcher-gnome not found  (aw_qt.manager:273)
2022-12-19 15:20:45 [ERROR]: Manager tried to start nonexistent module aw-watcher-gnome  (aw_qt.manager:265)

```

**Comment by flexagoon** [comment]
Thanks for the feedback! I'm currently busy, but I'll fix those issues as soon as I can.

> Where should I put this exactly? I tried to put in config folder and opt/activity-watch but no luck

In the Directory where you installed ActivityWatch, where the aw-qt binary is located. 

> I came across your gnome shell extension, is that meant to be installed with that watcher or something different?

Yes, the extension was created for the watcher and the watcher depends on it.

> In step 5, you mentioned the edits in the toml file. But should I uncomment these lines? Maybe this is a common knowledge of toml files but I guess there will be a plenty of people that don't know that. I did learn that answer with a couple of trial and errors.

Yes, you should uncomment them. Sorry for not mentioning it.

> Manager tried to start nonexistent module aw-watcher-gnome

Did you try putting the folder in `/opt/activitywatch`? If you did and that didn't work, try the [data directory](https://docs.activitywatch.net/en/latest/directories.html#data-directory)

**Comment by flexagoon** [comment]
@okan-instrumentl

**Comment by okan-instrumentl** [comment]
Thanks! It looks like it was my mistake, I did copy the wrong `aw-watcher-gnome` folder. I put it on `/opt/activitywatch` folder and after installing gnome extension, it works well.

Thanks for your hard work

**Comment by flexagoon** [comment]
Thanks for checking my project out!

(I'll reopen this issue as a reminder for myself to fix the issues)

**Comment by flexagoon** [comment]
I added mentions of the extension and the commented lines to the README. Feel free to re-open this if there are still problems.
