### ISSUE TITLE
How to disable window watcher

### ISSUE THREAD

**Issue by Thinkpiet** [flexagoon/aw-watcher-gnome#4]
Hi,

I want only the AFK watcher. But when I install this, I get both, AFK and window watcher. (And they work fine :-) )

How to disable the window watcher?

Best, Piet

**Comment by flexagoon** [comment]
Hi, this is not officially supported, as this is meant to be a full watcher for GNOME. If you want to disable the window watcher, you can just remove the bucket intialization in `window.py` (lines 55-57), and then remove the call to the window heartbeat function (line 120)

**Comment by Thinkpiet** [comment]
You meant watcher.py. Yes, I did that, it works perfectly! Thank you!
