### ISSUE TITLE
[IMPORTANT] Potentially deprecate this in favor of awatcher?

### ISSUE THREAD

**Issue by flexagoon** [flexagoon/aw-watcher-gnome#5]
Since I'm not actively maintaining this, I'm thinking about deprecating this watcher and directing people to use [awatcher](https://github.com/2e3s/awatcher) instead. It seems to be more actively maintained and has more features (eg. custom filter rules, while aw-watcher-gnome only has [hardcoded filters for Telegram and VSCode](https://github.com/flexagoon/aw-watcher-gnome/blob/main/aw_watcher_gnome/windows.py) which can only be changed through changing the source code.)

@2e3s what do you think?

**Comment by 2e3s** [comment]
I'm still maintaining **awatcher** indeed, with apparently working Gnome support, both idle and active window. Thanks for your idea of the watcher, I'll still refer to [your Gnome extension](https://github.com/flexagoon/focused-window-dbus) for now if you're not taking it down. I looked into embedding it like the KWin script but it's much more complex and very low priority.

**Comment by flexagoon** [comment]
@2e3s yes, I will be keeping and updating the extension - a bunch of other projects beside AW watchers depend on it, and it doesn't require that much maintenance.

I'll try to migrate to awatcher myself and test it for a while, and if it works without any issues, I'll archive this repository.

**Comment by 2e3s** [comment]
I'll be happy for any bug report, because I don't use Gnome. I used a virtual machine with a fresh install to test it, so not much of heterogeneity.

**Comment by flexagoon** [comment]
I've been using awatcher for a while now, and it works great, so I think I'll just archive this repository.
